describe('Atualizando receita', () => {
    it('Atualizando o nome com sucesso', () => {
        cy.visit('/');
        cy.get('#username').type('cypress')
        cy.get('#password').type('123abc')
        cy.get('button').click()
        cy.get('.card').click()
        cy.get('#nome').type('Chocolate quente')
        cy.wait(2000)
        cy.get('#ingredientes').type('Chocolate e leite integral.')
        cy.get('#modo_preparo').type('Aqueça o leite, acrescente o chocolate e misture bem.')
        cy.get('#comentarios').type('Bom para tomar no frio.')
        cy.get('.button').click()
        cy.get('h2').last().invoke('text').should('have.string', "Chocolate quente")
        cy.wait(2000)
        cy.get('h2').last().click()
        cy.get('h1').last().invoke('text').should('have.string', "Chocolate quente")
        cy.get('#card > :nth-child(3)').last().invoke('text').should('have.string', "Chocolate e leite integral.")
        cy.get('#card > :nth-child(5)').last().invoke('text').should('have.string', "Aqueça o leite, acrescente o chocolate e misture bem.")
        cy.get('#card > :nth-child(7)').last().invoke('text').should('have.string', "Bom para tomar no frio.")
        cy.wait(5000)
        cy.get('#lapis').click()
        cy.wait(2000)
        cy.get('#nome').clear().type('Chocolate frio')
        cy.wait(2000)
        cy.get('.button').click()
        cy.wait(2000)
        cy.get('h1').invoke('text').should('have.string', "Chocolate frio")
        cy.wait(5000)
    })

    it('Atualizando o modo de preparo com sucesso', () => {
        cy.visit('/');
        cy.get('#username').type('cypress')
        cy.get('#password').type('123abc')
        cy.get('button').click()
        cy.get('.card').click()
        cy.get('#nome').type('Chocolate quente')
        cy.get('#ingredientes').type('Chocolate e leite integral.')
        cy.get('#modo_preparo').type('Aqueça o leite, acrescente o chocolate e misture bem.')
        cy.wait(2000)
        cy.get('#comentarios').type('Bom para tomar no frio.')
        cy.get('.button').click()
        cy.get('h2').last().invoke('text').should('have.string', "Chocolate quente")
        cy.wait(2000)
        cy.get('h2').last().click()
        cy.get('h1').last().invoke('text').should('have.string', "Chocolate quente")
        cy.get('#card > :nth-child(3)').last().invoke('text').should('have.string', "Chocolate e leite integral.")
        cy.get('#card > :nth-child(5)').last().invoke('text').should('have.string', "Aqueça o leite, acrescente o chocolate e misture bem.")
        cy.get('#card > :nth-child(7)').last().invoke('text').should('have.string', "Bom para tomar no frio.")
        cy.wait(2000)
        cy.get('#lapis').click()
        cy.wait(1000)
        cy.get('#modo_preparo').clear().type('Coloque o leite aquecido direto no chocolate na caneca e misture.')
        cy.wait(2000)
        cy.get('.button').click()
        cy.wait(2000)
        cy.get('#card > :nth-child(5)').invoke('text').should('have.string', "Coloque o leite aquecido direto no chocolate na caneca e misture.")
        cy.wait(5000)
    })

    it('Esquecendo de colocar os ingredientes novos depois de ter apagado os ingredientes antigos', () => {
        cy.visit('/');
        cy.get('#username').type('cypress')
        cy.get('#password').type('123abc')
        cy.get('button').click()
        cy.get('.card').click()
        cy.get('#nome').type('Chocolate quente')
        cy.get('#ingredientes').type('Chocolate e leite integral.')
        cy.get('#modo_preparo').type('Aqueça o leite, acrescente o chocolate e misture bem.')
        cy.get('#comentarios').type('Bom para tomar no frio.')
        cy.get('.button').click()
        cy.get('h2').last().invoke('text').should('have.string', "Chocolate quente")
        cy.get('h2').last().click()
        cy.get('h1').last().invoke('text').should('have.string', "Chocolate quente")
        cy.get('#card > :nth-child(3)').last().invoke('text').should('have.string', "Chocolate e leite integral.")
        cy.get('#card > :nth-child(5)').last().invoke('text').should('have.string', "Aqueça o leite, acrescente o chocolate e misture bem.")
        cy.get('#card > :nth-child(7)').last().invoke('text').should('have.string', "Bom para tomar no frio.")
        cy.wait(2000)
        cy.get('#lapis').click()
        cy.get('#ingredientes').clear()
        cy.wait(2000)
        cy.get('.button').click()
        cy.get('#ingredientes').invoke('text').should('have.string', "")
        cy.wait(5000)
    })
})