describe('Filtrando por tags', () => {
    it('Filtrar por tag', () => {
        cy.visit('/');
        cy.wait(2000)
        cy.get('#username').type('cypress2')
        cy.get('#password').type('123abc')
        cy.wait(2000)
        cy.get('button').click()
        cy.wait(5000)
        cy.get('ul > :nth-child(3) > a').click()
        cy.wait(2000)
        cy.get('.button').click()
        cy.wait(2000)
        cy.get('#nome').type('bebidas')
        cy.wait(2000)
        cy.get('[action="/criar_tag/"] > button').click()
        cy.wait(2000)
        cy.get('img').click()
        cy.wait(2000)
        cy.get('.card').click()
        cy.wait(2000)
        cy.get('#nome').type('chocolate quente')
        cy.wait(2000)
        cy.get('#ingredientes').type('Chocolate e leite integral.')
        cy.get('#modo_preparo').type('Aqueça o leite, acrescente o chocolate e misture bem.')
        cy.get('#comentarios').type('Bom para tomar no frio.')
        cy.wait(2000)
        cy.get('#tags').click()
        cy.wait(2000)
        cy.get('[value=""]').click()
        cy.wait(2000)
        cy.get('.button').click()
        cy.get('h2').last().invoke('text').should('have.string', "chocolate quente")
        cy.wait(5000)

    })

    it('Excluir tags de receita', () => {
        cy.visit('/');
        cy.wait(2000)
        cy.get('#username').type('cypress2')
        cy.get('#password').type('123abc')
        cy.wait(2000)
        cy.get('button').click()
        cy.wait(5000)
        cy.get('ul > :nth-child(3) > a').click()
        cy.wait(2000)
        cy.get('.button').click()
        cy.wait(2000)
        cy.get('#nome').type('bebidas')
        cy.wait(2000)
        cy.get('[action="/criar_tag/"] > button').click()
        cy.wait(2000)
        cy.get('img').click()
        cy.wait(2000)
        cy.get('.card').click()
        cy.wait(2000)
        cy.get('#nome').type('chocolate quente')
        cy.wait(2000)
        cy.get('#ingredientes').type('Chocolate e leite integral.')
        cy.get('#modo_preparo').type('Aqueça o leite, acrescente o chocolate e misture bem.')
        cy.get('#comentarios').type('Bom para tomar no frio.')
        cy.wait(2000)
        cy.get('#tags').click()
        cy.wait(2000)
        cy.get('[value=""]').click()
        cy.wait(2000)
        cy.get('.button').click()
        cy.get('h2').last().invoke('text').should('have.string', "chocolate quente")
        cy.wait(5000)
    })

    it('Tentando pesquisar tags sem ter', () => {
        cy.visit('/');
        cy.wait(2000)
        cy.get('#username').type('cypress2')
        cy.get('#password').type('123abc')
        cy.wait(2000)
        cy.get('button').click()
        cy.wait(5000)
        cy.get('.card').click()
        cy.wait(2000)
        cy.get('#nome').type('chocolate quente')
        cy.wait(2000)
        cy.get('#ingredientes').type('Chocolate e leite integral.')
        cy.get('#modo_preparo').type('Aqueça o leite, acrescente o chocolate e misture bem.')
        cy.get('#comentarios').type('Bom para tomar no frio.')
        cy.wait(2000)
        cy.get('.button').click()
        cy.get('h2').last().invoke('text').should('have.string', "chocolate quente")
        cy.wait(5000)
        cy.get('header > form > input').type('bebidas geladas')
        cy.wait(2000)
        cy.get('header > form > button').click()
    })
})