describe('Sugestões de receita', () => {
    it('Visualizar receita sugerida', () => {
        cy.visit('/usuarios/delete_cypress/');
        cy.get('.button').click()
        cy.visit('/');
        cy.wait(5000)
        cy.get('a').click()
        cy.get('#username').type('Receitopedia')
        cy.get('#password').type('123abc')
        cy.get('#password_confirm').type('123abc')
        cy.wait(2000)
        cy.get('.button').click()
        cy.get('#username').type('Receitopedia')
        cy.get('#password').type('123abc')
        cy.wait(2000)
        cy.get('.button').click()
        cy.wait(2000)
        cy.get('.card').click()
        cy.get('#nome').type('chocolate quente')
        cy.get('#ingredientes').type('Chocolate e leite integral.')
        cy.get('#modo_preparo').type('Aqueça o leite, acrescente o chocolate e misture bem.')
        cy.get('#comentarios').type('Bom para tomar no frio.')
        cy.get('.button').click()
        cy.get('h2').last().invoke('text').should('have.string', "chocolate quente")
        cy.wait(2000)
        cy.get('.logout-button').click()
        cy.wait(1000)
        cy.get('a').click()
        cy.wait(1000)
        cy.get('a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('123abc')
        cy.get('#password_confirm').type('123abc')
        cy.wait(1000)
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('123abc')
        cy.wait(1000)
        cy.get('.button').click()
        cy.wait(5000)
        cy.get('ul > :nth-child(4) > a').click()
        cy.get('h3').invoke('text').should('have.string', "chocolate quente")
        cy.get('h5').invoke('text').should('have.string', "Receitopedia (oficial!)")
        cy.wait(5000)
    })

    it('Adicionando sugestão a minhas receitas', () => {
        cy.visit('/usuarios/delete_cypress/');
        cy.get('.button').click()
        cy.visit('/');
        cy.get('a').click()
        cy.get('#username').type('Receitopedia')
        cy.get('#password').type('123abc')
        cy.get('#password_confirm').type('123abc')
        cy.get('.button').click()
        cy.get('#username').type('Receitopedia')
        cy.get('#password').type('123abc')
        cy.get('.button').click()
        cy.get('.card').click()
        cy.get('#nome').type('chocolate quente')
        cy.get('#ingredientes').type('Chocolate e leite integral.')
        cy.get('#modo_preparo').type('Aqueça o leite, acrescente o chocolate e misture bem.')
        cy.get('#comentarios').type('Bom para tomar no frio.')
        cy.get('.button').click()
        cy.get('h2').last().invoke('text').should('have.string', "chocolate quente")
        cy.get('.logout-button').click()
        cy.get('a').click()
        cy.get('a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('123abc')
        cy.get('#password_confirm').type('123abc')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('123abc')
        cy.get('.button').click()
        cy.wait(5000)
        cy.get('ul > :nth-child(4) > a').click()
        cy.get('h3').invoke('text').should('have.string', "chocolate quente")
        cy.get('h5').invoke('text').should('have.string', "Receitopedia (oficial!)")
        cy.wait(2000)
        cy.get('.fas').click()
        cy.get(':nth-child(1) > a').click()
        cy.get('h2').last().invoke('text').should('have.string', "chocolate quente")
        cy.wait(5000)
    })

    it('Tentando adicionar sugestão que já foi adicionada', () => {
        cy.visit('/usuarios/delete_cypress/');
        cy.get('.button').click()
        cy.visit('/');
        cy.get('a').click()
        cy.get('#username').type('Receitopedia')
        cy.get('#password').type('123abc')
        cy.get('#password_confirm').type('123abc')
        cy.get('.button').click()
        cy.get('#username').type('Receitopedia')
        cy.get('#password').type('123abc')
        cy.get('.button').click()
        cy.get('.card').click()
        cy.get('#nome').type('chocolate quente')
        cy.get('#ingredientes').type('Chocolate e leite integral.')
        cy.get('#modo_preparo').type('Aqueça o leite, acrescente o chocolate e misture bem.')
        cy.get('#comentarios').type('Bom para tomar no frio.')
        cy.get('.button').click()
        cy.get('h2').last().invoke('text').should('have.string', "chocolate quente")
        cy.get('.logout-button').click()
        cy.get('a').click()
        cy.get('a').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('123abc')
        cy.get('#password_confirm').type('123abc')
        cy.get('.button').click()
        cy.get('#username').type('cypress')
        cy.get('#password').type('123abc')
        cy.get('.button').click()
        cy.wait(2000)
        cy.get('ul > :nth-child(4) > a').click()
        cy.get('h3').invoke('text').should('have.string', "chocolate quente")
        cy.get('h5').invoke('text').should('have.string', "Receitopedia (oficial!)")
        cy.wait(2000)
        cy.get('.fas').click()
        cy.get(':nth-child(1) > a').click()
        cy.get('h2').last().invoke('text').should('have.string', "chocolate quente")
        cy.wait(2000)
        cy.get('ul > :nth-child(4) > a').click()
        cy.wait(2000)
        cy.get('.fas').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > a').click()
        cy.get('h2').should('have.length', 1)
        cy.wait(5000)
    })
})