# Generated by Django 5.1.1 on 2024-09-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo1', models.CharField(max_length=50)),
                ('tipo2', models.CharField(blank=True, max_length=50, null=True)),
                ('hp', models.IntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.TextField()),
                ('imagem', models.URLField()),
            ],
        ),
    ]
