# Generated by Django 5.1.1 on 2024-09-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='nome',
            new_name='danilo',
        ),
    ]
