# Generated by Django 5.1.1 on 2024-09-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0002_rename_nome_pokemon_danilo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='danilo',
            new_name='nome',
        ),
    ]
