# Generated by Django 4.2.14 on 2024-09-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_receita_ingredientes_receita_modo_preparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='comentarios',
            field=models.TextField(default='Comentarios não informados'),
        ),
    ]
