# Generated by Django 4.2.14 on 2024-09-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_receita_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='estrelas',
            field=models.TextField(default='Estrelas não informadas'),
        ),
    ]
