# Generated by Django 5.1.1 on 2024-09-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_receita_estrelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='estrelas',
        ),
        migrations.AlterField(
            model_name='receita',
            name='comentarios',
            field=models.TextField(default='Comentários não informados'),
        ),
    ]
