# Generated by Django 5.1.2 on 2024-10-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0008_pasta_receita_pasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(default='Modo de preparo não informado'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
