# Generated by Django 5.1.2 on 2024-11-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0010_receita_sugestao_receitasalva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='tags',
            field=models.ManyToManyField(blank=True, to='aplicacao.tag'),
        ),
    ]
