# Generated by Django 5.1.2 on 2024-11-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0015_alter_tag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
